import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(23,GPIO.OUT)
GPIO.setup(16,GPIO.OUT)
for i in range(20):
  GPIO.output(23, GPIO.HIGH)
  time.sleep(0.3)
  GPIO.output(23, GPIO.LOW)
  time.sleep(0.3)
  GPIO.output(23, GPIO.HIGH)
  time.sleep(0.3)
  GPIO.output(23, GPIO.LOW)
  time.sleep(0.3)
  GPIO.output(23, GPIO.HIGH)
  time.sleep(0.3)
  GPIO.output(23, GPIO.LOW)
  time.sleep(0.3)
  GPIO.output(16,GPIO.HIGH)
  time.sleep(0.1)
  GPIO.output(16,GPIO.LOW)
  time.sleep(0.1)
  GPIO.output(16,GPIO.HIGH)
  time.sleep(0.1)
  GPIO.output(16,GPIO.LOW)
  time.sleep(0.1)
  GPIO.output(16,GPIO.HIGH)
  time.sleep(0.6)
  GPIO.output(16,GPIO.LOW)